<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Samples.Layout</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Friflo.Engine.ECS" Version="3.4.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.csproj" />
        <ProjectReference Include="..\..\CrucibleUI\CrucibleUI.csproj" />
        <ProjectReference Include="..\..\Ignis.Core\Ignis.Core.csproj" />
        <ProjectReference Include="..\..\Ignis.Graphics\Ignis.Graphics.csproj" />
        <ProjectReference Include="..\..\Ignis.Graphics.Backends.OpenGL\Ignis.Graphics.Backends.OpenGL.csproj" />
    </ItemGroup>

</Project>

